[
  {
    "pk": 1, 
    "model": "api.requestlog", 
    "fields": {
      "domain": "", 
      "uuid": "74163ee1-ec34-4295-8fa4-05bb92a172e0", 
      "level": "DEBUG", 
      "timestamp": "2012-08-07 08:39:39", 
      "uri": "/api/procedure/", 
      "duration": 0.011089086532592773, 
      "device": "", 
      "message": "[{\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.000s\", \"timestamp\": 1344346779.03, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.003) SELECT \\\"api_procedure\\\".\\\"id\\\", \\\"api_procedure\\\".\\\"uuid\\\", \\\"api_procedure\\\".\\\"name\\\", \\\"api_procedure\\\".\\\"author\\\", \\\"api_procedure\\\".\\\"version\\\", \\\"api_procedure\\\".\\\"concept_id\\\", \\\"api_procedure\\\".\\\"src\\\", \\\"api_procedure\\\".\\\"created\\\", \\\"api_procedure\\\".\\\"modified\\\" FROM \\\"api_procedure\\\"; args=()\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.004s\", \"timestamp\": 1344346779.04, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.001) SELECT \\\"api_concept\\\".\\\"id\\\", \\\"api_concept\\\".\\\"uuid\\\", \\\"api_concept\\\".\\\"name\\\", \\\"api_concept\\\".\\\"display_name\\\", \\\"api_concept\\\".\\\"description\\\", \\\"api_concept\\\".\\\"conceptclass\\\", \\\"api_concept\\\".\\\"datatype\\\", \\\"api_concept\\\".\\\"mimetype\\\", \\\"api_concept\\\".\\\"constraint\\\", \\\"api_concept\\\".\\\"created\\\", \\\"api_concept\\\".\\\"modified\\\" FROM \\\"api_concept\\\" WHERE \\\"api_concept\\\".\\\"id\\\" = 3 ; args=(3,)\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 28, \"level_number\": 40, \"delta\": \"0.006s\", \"timestamp\": 1344346779.04, \"level_name\": \"ERROR\", \"function_name\": \"process_exception\", \"message\": \"An unhandled exception occurred: TypeError('resource_uri() takes no arguments (1 given)',)\", \"module\": \"middleware\", \"filename\": \"middleware.py\"}]"
    }
  }, 
  {
    "pk": 2, 
    "model": "api.requestlog", 
    "fields": {
      "domain": "", 
      "uuid": "be815d13-2714-4b64-ac10-2a03d55d6f9b", 
      "level": "DEBUG", 
      "timestamp": "2012-08-07 08:41:05", 
      "uri": "/api/procedure/", 
      "duration": 0.073882102966308594, 
      "device": "", 
      "message": "[{\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.000s\", \"timestamp\": 1344346865.92, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.002) SELECT \\\"api_procedure\\\".\\\"id\\\", \\\"api_procedure\\\".\\\"uuid\\\", \\\"api_procedure\\\".\\\"name\\\", \\\"api_procedure\\\".\\\"author\\\", \\\"api_procedure\\\".\\\"version\\\", \\\"api_procedure\\\".\\\"concept_id\\\", \\\"api_procedure\\\".\\\"src\\\", \\\"api_procedure\\\".\\\"created\\\", \\\"api_procedure\\\".\\\"modified\\\" FROM \\\"api_procedure\\\"; args=()\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.003s\", \"timestamp\": 1344346865.92, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.000) SELECT \\\"api_concept\\\".\\\"id\\\", \\\"api_concept\\\".\\\"uuid\\\", \\\"api_concept\\\".\\\"name\\\", \\\"api_concept\\\".\\\"display_name\\\", \\\"api_concept\\\".\\\"description\\\", \\\"api_concept\\\".\\\"conceptclass\\\", \\\"api_concept\\\".\\\"datatype\\\", \\\"api_concept\\\".\\\"mimetype\\\", \\\"api_concept\\\".\\\"constraint\\\", \\\"api_concept\\\".\\\"created\\\", \\\"api_concept\\\".\\\"modified\\\" FROM \\\"api_concept\\\" WHERE \\\"api_concept\\\".\\\"id\\\" = 3 ; args=(3,)\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 28, \"level_number\": 40, \"delta\": \"0.006s\", \"timestamp\": 1344346865.92, \"level_name\": \"ERROR\", \"function_name\": \"process_exception\", \"message\": \"An unhandled exception occurred: TypeError('resource_uri() takes no arguments (1 given)',)\", \"module\": \"middleware\", \"filename\": \"middleware.py\"}]"
    }
  }, 
  {
    "pk": 3, 
    "model": "api.requestlog", 
    "fields": {
      "domain": "", 
      "uuid": "48c56035-5cc3-41a6-92fb-98629043212e", 
      "level": "DEBUG", 
      "timestamp": "2012-08-07 12:20:50", 
      "uri": "/admin/api/requestlog/", 
      "duration": 0.11113405227661133, 
      "device": "", 
      "message": "[{\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.000s\", \"timestamp\": 1344360050.84, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.003) SELECT \\\"django_session\\\".\\\"session_key\\\", \\\"django_session\\\".\\\"session_data\\\", \\\"django_session\\\".\\\"expire_date\\\" FROM \\\"django_session\\\" WHERE (\\\"django_session\\\".\\\"session_key\\\" = c78bab02476693db331f2a292975e5af  AND \\\"django_session\\\".\\\"expire_date\\\" > 2012-08-07 12:20:50.830827 ); args=('c78bab02476693db331f2a292975e5af', u'2012-08-07 12:20:50.830827')\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.004s\", \"timestamp\": 1344360050.84, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.001) SELECT \\\"auth_user\\\".\\\"id\\\", \\\"auth_user\\\".\\\"username\\\", \\\"auth_user\\\".\\\"first_name\\\", \\\"auth_user\\\".\\\"last_name\\\", \\\"auth_user\\\".\\\"email\\\", \\\"auth_user\\\".\\\"password\\\", \\\"auth_user\\\".\\\"is_staff\\\", \\\"auth_user\\\".\\\"is_active\\\", \\\"auth_user\\\".\\\"is_superuser\\\", \\\"auth_user\\\".\\\"last_login\\\", \\\"auth_user\\\".\\\"date_joined\\\" FROM \\\"auth_user\\\" WHERE \\\"auth_user\\\".\\\"id\\\" = 1 ; args=(1,)\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.007s\", \"timestamp\": 1344360050.84, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.000) SELECT COUNT(*) FROM \\\"api_requestlog\\\"; args=()\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.011s\", \"timestamp\": 1344360050.85, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.001) SELECT \\\"api_requestlog\\\".\\\"id\\\", \\\"api_requestlog\\\".\\\"uuid\\\", \\\"api_requestlog\\\".\\\"device\\\", \\\"api_requestlog\\\".\\\"domain\\\", \\\"api_requestlog\\\".\\\"level\\\", \\\"api_requestlog\\\".\\\"uri\\\", \\\"api_requestlog\\\".\\\"message\\\", \\\"api_requestlog\\\".\\\"timestamp\\\", \\\"api_requestlog\\\".\\\"duration\\\" FROM \\\"api_requestlog\\\" ORDER BY \\\"api_requestlog\\\".\\\"id\\\" DESC; args=()\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 44, \"level_number\": 10, \"delta\": \"0.084s\", \"timestamp\": 1344360050.92, \"level_name\": \"DEBUG\", \"function_name\": \"execute\", \"message\": \"(0.000) SELECT \\\"auth_message\\\".\\\"id\\\", \\\"auth_message\\\".\\\"user_id\\\", \\\"auth_message\\\".\\\"message\\\" FROM \\\"auth_message\\\" WHERE \\\"auth_message\\\".\\\"user_id\\\" = 1 ; args=(1,)\", \"module\": \"util\", \"filename\": \"util.py\"}, {\"line_number\": 28, \"level_number\": 40, \"delta\": \"0.104s\", \"timestamp\": 1344360050.94, \"level_name\": \"ERROR\", \"function_name\": \"process_exception\", \"message\": \"An unhandled exception occurred: TemplateSyntaxError(u'Caught TypeError while rendering: coercing to Unicode: need string or buffer, __proxy__ found',)\", \"module\": \"middleware\", \"filename\": \"middleware.py\"}]"
    }
  }
]